##
# Copyright (c) 2025 Keve Müller <kevemueller@users.github.com>
#
# SPDX-License-Identifier: BSD-2-Clause
#

# GitHub action to perform a single build.

name: single build

"on":
  workflow_dispatch:
    inputs:
      branch:
        description: "branch"
        default: netbsd-10

permissions:
  contents: read

jobs:
  build1:
    name: ${{ matrix.branch }} on ${{ matrix.build-os }}
    runs-on: "${{ matrix.build-os }}"
    strategy:
      fail-fast: false
      matrix:
        build-os:
          - macos-15
          - macos-13
          - ubuntu-24.04
        branch:
          - ${{ inputs.branch }}

    steps:
      - name: env
        run: |
          echo uname -a: $(uname -a)
          echo uname -m: $(uname -m)
          echo uname -p: $(uname -p)
          echo "NPROC=$(getconf _NPROCESSORS_ONLN 2>/dev/null ||
            getconf NPROCESSORS_ONLN 2>/dev/null ||
            echo 1)" >> "${GITHUB_ENV}"
          echo "BUILD_D=$PWD/NetBSD.D" >> "${GITHUB_ENV}"
          echo "BUILD_T=$PWD/NetBSD.T" >> "${GITHUB_ENV}"
          echo "BUILD_M=$PWD/NetBSD.M" >> "${GITHUB_ENV}"
          echo "BUILD_O=$PWD/NetBSD.O" >> "${GITHUB_ENV}"

      - uses: actions/checkout@v4
        with:
          path: src
          ref: ${{ matrix.branch }}

      - name: build tools 
        run: |
          ./build.sh -U -u -j"${NPROC}" -D "${BUILD_D}" -M "${BUILD_M}" -O "${BUILD_O}" -m evbarm -a aarch64 tools
        working-directory: src